name: 'run-ormolu'
description: 'Check formatting of Haskell code with Ormolu'
inputs:
  pattern:
    required: false
    description: >
      Glob pattern that are used to find source files to format. It is
      possible to specify several patterns by putting each on a new line.
    default: |
      **/*.hs
      **/*.hs-boot
  respect-cabal-files:
    required: false
    description: >
      Whether to try to locate Cabal files and take into account their
      default-extensions and default-language settings.
    default: true
  follow-symbolic-links:
    required: false
    description: >
      Whether to follow symbolic links.
    default: true
  mode:
    required: false
    description: >
      Mode of operation: 'stdout', 'inplace', or 'check' (the default).
    default: 'check'
  extra-args:
    required: false
    description: >
      Extra arguments to pass to Ormolu.
  version:
    required: false
    description: >
      The version number of Ormolu to use. Defaults to "latest".
    default: latest
runs:
  using: 'node20'
  main: 'dist/index.js'
